// Affiliations of individual collaborators, not institutional endorsements.
export const academicNetwork = [
  {
    id: 'purdue',
    name: 'Purdue University',
    label: 'Purdue University',
    url: 'https://www.purdue.edu/',
    relationship: 'Research and community collaboration',
    logo: '/images/universities/purdue.svg',
    width: 248,
    height: 45,
  },
  {
    id: 'stanford',
    name: 'Stanford University',
    label: 'Stanford University',
    url: 'https://www.stanford.edu/',
    relationship: 'Collaborative robotics research',
    logo: '/images/universities/stanford.png',
    width: 426,
    height: 91,
  },
  {
    id: 'kth',
    name: 'KTH Royal Institute of Technology',
    label: 'KTH',
    url: 'https://www.kth.se/en',
    relationship: 'Cross-cultural research collaboration',
    logo: '/images/universities/kth.svg',
    width: 502,
    height: 502,
  },
  {
    id: 'tu-wien',
    name: 'TU Wien',
    label: 'TU Wien',
    url: 'https://www.tuwien.at/en/',
    relationship: 'Academic exchange and project development',
    logo: '/images/universities/tu-wien.svg',
    width: 97,
    height: 97,
  },
  {
    id: 'snu',
    name: 'Seoul National University',
    label: 'Seoul National University',
    url: 'https://en.snu.ac.kr/',
    relationship: 'Cross-cultural study planning',
    logo: '/images/universities/snu.png',
    width: 156,
    height: 66,
  },
  {
    id: 'ntu',
    name: 'National Taiwan University',
    label: 'National Taiwan University',
    url: 'https://www.ntu.edu.tw/english/',
    relationship: 'Multi-site study development',
    logo: '/images/universities/ntu.svg',
    width: 442,
    height: 69,
  },
  {
    id: 'musashino',
    name: 'Musashino University',
    label: 'Musashino University',
    url: 'https://www.musashino-u.ac.jp/',
    relationship: 'Multi-site study development',
    logo: '/images/universities/musashino.png',
    width: 400,
    height: 300,
  },
  {
    id: 'uncw',
    name: 'University of North Carolina Wilmington',
    label: 'UNC Wilmington',
    url: 'https://www.uncw.edu/',
    relationship: 'Research collaboration and study development',
    logo: '/images/universities/uncw.svg',
    width: 222,
    height: 222,
  },
  {
    id: 'okstate',
    name: 'Oklahoma State University',
    label: 'Oklahoma State University',
    url: 'https://go.okstate.edu/',
    relationship: 'Study planning and project development',
    logo: '/images/universities/okstate.svg',
    width: 164,
    height: 85,
  },
  {
    id: 'eth',
    name: 'ETH Zurich',
    label: 'ETH Zurich',
    url: 'https://ethz.ch/en.html',
    relationship: 'Academic exchange and exploratory collaboration',
    logo: '/images/universities/eth.svg',
    width: 120,
    height: 20,
  },
  {
    id: 'uzh',
    name: 'University of Zurich',
    label: 'University of Zurich',
    url: 'https://www.uzh.ch/en.html',
    relationship: 'Digital-health academic exchange',
    logo: '/images/universities/uzh.svg',
    width: 154,
    height: 53,
  },
  {
    id: 'st-gallen',
    name: 'University of St. Gallen',
    label: 'University of St. Gallen',
    url: 'https://www.unisg.ch/en/',
    relationship: 'Digital-health academic exchange',
    logo: '/images/universities/st-gallen.svg',
    width: 189,
    height: 40,
  },
  {
    id: 'hawaii',
    name: 'University of Hawaii at Manoa',
    label: 'University of Hawaii at Manoa',
    url: 'https://manoa.hawaii.edu/',
    relationship: 'Caregiving project concept development',
    logo: '/images/universities/hawaii.png',
    width: 2237,
    height: 244,
  },
  {
    id: 'twu',
    name: "Texas Woman's University",
    label: "Texas Woman's University",
    url: 'https://twu.edu/',
    relationship: 'Co-design teaching and research proposal development',
    logo: '/images/universities/twu.svg',
    width: 263,
    height: 32,
  },
];
